configuration:
  - "Release (DLL)"


environment:
  BINTRAY_USER:
    secure: 9iEGe4JL2hgRpnU8mx5QcQ==
  BINTRAY_APIKEY:
    secure: ES2msT1RuviApoNuuliFo4lr05APq+mG6Rx9XCO5swkUpvyxR2kc7af4WCqfnxmv


init:
  - cmd: echo "################"
  - cmd: echo "###   INIT   ###"
  - cmd: echo "################"


before_build:
  - cmd: echo "########################"
  - cmd: echo "###   BEFORE BUILD   ###"
  - cmd: echo "########################"
  - cmd: echo ""
  - cmd: echo %cd%'

  ### INSTALLING DEPENDENCIES
  - cmd: mkdir libs
  - cmd: cd libs

  - cmd: echo "##########################"
  - cmd: echo "###   INSTALLING GLM   ###"
  - cmd: echo "##########################"
  - cmd: git clone -b 0.9.5 --depth 1 https://github.com/g-truc/glm.git glm-0.9.5.4/
  - cmd: mkdir glm-0.9.5.4\include
  - cmd: move glm-0.9.5.4\glm glm-0.9.5.4\include\glm

  - cmd: echo "###########################"
  - cmd: echo "###   INSTALLING GLEW   ###"
  - cmd: echo "###########################"
  - cmd: appveyor DownloadFile https://www.dropbox.com/s/psb96votnpm6ulw/glew-1.12.0.zip?dl=1 -FileName glew.zip
  - cmd: 7z x glew.zip

  - cmd: echo "###########################"
  - cmd: echo "###   INSTALLING GLFW   ###"
  - cmd: echo "###########################"
  - cmd: appveyor DownloadFile https://github.com/glfw/glfw/releases/download/3.1/glfw-3.1.bin.WIN32.zip -FileName glfw.zip
  - cmd: 7z x glfw.zip
  - cmd: move glfw-3.1.bin.WIN32 glfw-3.1

  - cmd: echo "################################"
  - cmd: echo "###   INSTALLING FREETYPE2   ###"
  - cmd: echo "################################"
  - cmd: appveyor DownloadFile https://www.dropbox.com/s/6kvjny8dgt0dkai/freetype-2.5.5.zip?dl=1 -FileName freetype2.zip
  - cmd: 7z x freetype2.zip

  - cmd: echo "##############################"
  - cmd: echo "###   INSTALLING LIBJPEG   ###"
  - cmd: echo "##############################"
  - cmd: appveyor DownloadFile https://www.dropbox.com/s/rtjlezqqqny3lr0/jpeg-9a.rar?dl=1 -FileName libjpeg.zip
  - cmd: 7z x libjpeg.zip

  - cmd: echo "#############################"
  - cmd: echo "###   INSTALLING LIBPNG   ###"
  - cmd: echo "#############################"
  - cmd: appveyor DownloadFile https://www.dropbox.com/s/5081ts8grc90xkj/libpng-1.6.17.rar?dl=1 -FileName libpng.zip
  - cmd: 7z x libpng.zip

  - cmd: echo "###########################"
  - cmd: echo "###   INSTALLING ZLIB   ###"
  - cmd: echo "###########################"
  - cmd: appveyor DownloadFile https://www.dropbox.com/s/857rpc08be1ya82/zlib-1.2.8.rar?dl=1 -FileName zlib.zip
  - cmd: 7z x zlib.zip

  - cmd: echo "############################"
  - cmd: echo "###   INSTALLING GTEST   ###"
  - cmd: echo "############################"
  - cmd: appveyor DownloadFile https://www.dropbox.com/s/z74oruxw6syaua8/gtest-1.7.0.rar?dl=1 -FileName gtest.zip
  - cmd: 7z x gtest.zip

  ### ENDING INSTALLATION ###
  - cmd: cd ..


test_script:
  ### RUN UNIT TESTS ###
  - cmd: echo "######################"
  - cmd: echo "###   UNIT TESTS   ###"
  - cmd: echo "######################"
  - cmd: cd tests\bin
  - cmd: move "Unit tests.exe" "unit_tests.exe" # required to have no space in name
  - cmd: unit_tests.exe
  - cmd: cd ..\..


before_deploy:
  ### BUILDING EXTRA CONFIGURATIONS TO DEPLOY ###
  - cmd: MSBuild "project\msvc\GLUL\GLUL.vcxproj" /p:Configuration="Debug"
  - cmd: MSBuild "project\msvc\GLUL\GLUL.vcxproj" /p:Configuration="Release"
  - cmd: MSBuild "project\msvc\GLUL\GLUL.vcxproj" /p:Configuration="Debug (DLL)"
  - cmd: MSBuild "project\msvc\GLUL\GLUL.vcxproj" /p:Configuration="Release (DLL)"


deploy_script:
  ### DEPLOYING ###
  - cmd: echo "#####################"
  - cmd: echo "###   DEPLOYING   ###"
  - cmd: echo "#####################"

  # Directories & variables
  - cmd: set DEPLOY_NAME=GLUL-msvc-win32-%APPVEYOR_REPO_BRANCH%.latest
  - cmd: if [%APPVEYOR_REPO_TAG%]==[true] set DEPLOY_NAME=GLUL-%APPVEYOR_REPO_TAG_NAME%-msvc-win32 # If this build is for tagged commit, deploy only tag package
  - cmd: set DEPLOY_NAME_FILE=%DEPLOY_NAME%.7z
  - cmd: set DEPLOY_DIR_1=deploy
  - cmd: set DEPLOY_DIR_2=%DEPLOY_DIR_1%\windows
  - cmd: set DEPLOY_DIR_FULL=%DEPLOY_DIR_2%\%DEPLOY_NAME%

  # Create directory and clone clean repository
  - cmd: git clone --depth 1 --branch=%APPVEYOR_REPO_BRANCH% https://github.com/%APPVEYOR_REPO_NAME% "%DEPLOY_DIR_FULL%"

  # Copy necessary folders and files
  - cmd: XCOPY /E /Y bin "%DEPLOY_DIR_FULL%\bin"
  - cmd: XCOPY /E /Y examples "%DEPLOY_DIR_FULL%\examples"
  - cmd: XCOPY /E /Y tests "%DEPLOY_DIR_FULL%\tests"

  # Remove unnecessary folders and files
  - cmd: RMDIR /S /Q "%DEPLOY_DIR_FULL%\.git"         # REMOVE GIT REPO
  - cmd: DEL /Q "%DEPLOY_DIR_FULL%\.gitignore"        # REMOVE .gitignore
  - cmd: DEL /Q "%DEPLOY_DIR_FULL%\*.yml"             # REMOVE all .yml files (Travis, AppVeyor etc.)
  - cmd: DEL /Q "%DEPLOY_DIR_FULL%\*.json"            # REMOVE all .json files (Bintray etc.)
  - cmd: DEL /Q /S "%DEPLOY_DIR_FULL%\bin\*.exp"      # REMOVE all .exp files from bin
  - cmd: DEL /Q /S "%DEPLOY_DIR_FULL%\*.ilk"          # REMOVE all .exp files from examples and tests
  - cmd: DEL /Q /S "%DEPLOY_DIR_FULL%\*.pdb"          # REMOVE all .exp files from examples and tests
  - cmd: DEL /Q /S "%DEPLOY_DIR_FULL%\examples\*.dll" # REMOVE all .dll files from examples (copies of library's dll)
  - cmd: DEL /Q /S "%DEPLOY_DIR_FULL%\tests\*.dll"    # REMOVE all .dll files from tests (copy of library's dll)

  # Add build info
  - cmd: echo "Build id - %APPVEYOR_BUILD_ID% (#%APPVEYOR_BUILD_NUMBER%)" > "%DEPLOY_DIR_FULL%\BuildInfo.txt"
  - cmd: echo "Branch - %APPVEYOR_REPO_BRANCH%" >> "%DEPLOY_DIR_FULL%\BuildInfo.txt"
  - cmd: echo "Date of build - " >> "%DEPLOY_DIR_FULL%\BuildInfo.txt"
  - cmd: DATE /T >> "%DEPLOY_DIR_FULL%\BuildInfo.txt"
  - cmd: TIME /T >> "%DEPLOY_DIR_FULL%\BuildInfo.txt"

  # Go to deploy directory
  - cmd: cd "%DEPLOY_DIR_2%"

  # Create package to upload
  - cmd: 7z a -t7z -r -m0=LZMA2 -mx=9 "%DEPLOY_NAME_FILE%" ./*
  - cmd: echo "Package %DEPLOY_NAME% created..."

  # Deploy variables
  - cmd: set BINTRAY_REPO=generic
  - cmd: set BINTRAY_PACKAGE=GLUL
  - cmd: set BINTRAY_VERSION=0.3
  - cmd: set BINTRAY_PATH=%BINTRAY_USER%/%BINTRAY_REPO%/%BINTRAY_PACKAGE%/%BINTRAY_VERSION%
  - cmd: set BINTRAY_PATH_FULL=%BINTRAY_PATH%/windows/%DEPLOY_NAME_FILE%

  # Deploy package
  - cmd: curl -fsS -u "%BINTRAY_USER%:%BINTRAY_APIKEY%" -X PUT "https://api.bintray.com/content/%BINTRAY_PATH_FULL%?override=1&publish=1" --data-binary @%DEPLOY_NAME_FILE%
  - cmd: echo "Deployed package!"

  # Return to build directory and finish deploying
  - cmd: cd "%APPVEYOR_BUILD_FOLDER%"
